v 1.2.1: small fix
* correctly allocate/deallocate loop drives if more than one virtual drive is specified on the command line

v 1.2: new algorithm

* completely reworked and better algorithm

diff --git a/confinedrv b/confinedrv
--- a/confinedrv
+++ b/confinedrv
@@ -1,10 +1,16 @@
 #!/bin/bash
 #
-# confinedrv v1.1
-# (c) copyright by Elmar Stellnberger 2009, Jan 2010
+# confinedrv v1.2.1
+# (c) copyright by Elmar Stellnberger, the original author: 2009, Jan 2010
 #
 #  further information: www.elstel.org/com; look here for an actual contact address
 #  current email: estellnb@elstel.org; additional email estellnb@gmail.com
+#
+# v 1.2.1: small fix (17.11.2013)
+#  * correctly allocate/deallocate loop drives if more than one virtual drive is specified on the command line
+#
+# v 1.2: new algorithm (17.11.2013)
+#  * completely reworked and better algorithm
 #
 # v 1.1: added license (30.10.2013)
 #  * better option parsing; some minor fixes
@@ -74,13 +80,96 @@ if [[ $# -le 0 ]]; then
   echo -e "$(basename "$0") --help/--license\n"
 fi
 
+getdevno() {
+  local attr x usr grp major minor rest
+  read attr x usr grp major minor rest < <(ls -l "$1";)
+  echo "${major%,}:$minor"
+}
+
+initloops() { local partno=$1
+
+  [[ -z "$rolp" && verbose -gt 0 ]] && echo $'\e[;33mconfinedrv - visit us on www.elstel.org/qemu\e[0m' >&2;
+
+  mkdir -p /dev/shm/
+  #bdev=$(getdevno /dev/$org)
+  if [[ partno -gt 0 ]]; then
+    loop=$(losetup -f)
+    losetup $loop /dev/$org
+  else loop="";
+  fi
+
+  rolp=$(losetup -f)
+  losetup -r $rolp /dev/$org
+  blockdev --setro $rolp
+  chmod gua-w $rolp >/dev/null 2>&1 
+
+  #echo "$dest $loop" >>/dev/shm/confinedrv-loops
+  # -> later
+}
+
+# device mapper can only control access in chunks of pagesize = 4096 = 2**3*512
+
 PAGE_SIZE=$(getconf PAGE_SIZE)
 [[ PAGE_SIZE -eq 0 ]] && { warn "assuming page size of 4096."; PAGE_SIZE=4096; }
 [[ PAGE_SIZE/512*512 -ne PAGE_SIZE ]] && { err "page size not divisable by 512; exiting."; exit 222; }
-let PGspare=PAGE_SIZE/512-1
+let PGsize=PAGE_SIZE/512
+let PGspare=PGsize-1
+
+IssuePartRegion() { # access start end
+  local access=$1 start=$2 end=$3 length; let length=end-start
+  [[ access -lt 0 ]] && return
+  if [[ access -ge 2 ]]; then echo "$start $length linear $loop $start" >&8
+  elif [[ access -eq 1 ]]; then echo "$start $length linear $rolp $start" >&8
+  else echo "$start $length error" >&8
+  fi
+}
+
+roundup() { echo  $(( ($1+PGspare) / PGsize * PGsize )); }
+rounddown() { echo  $(( ($1) / PGsize * PGsize )); }
+min() { if [[ $1 -le $2 ]]; then echo $1; else echo $2; fi }
+max() { if [[ $1 -ge $2 ]]; then echo $1; else echo $2; fi }
+acc2str() { if [[ $1 -ge 2 ]]; then echo "rw"; elif [[ $1 -eq 1 ]]; then echo "r"; else echo "-"; fi }
+
+NotePartRegion() {
+  local access=$1 start=$2 end=$3
+  [[ start -le end ]] || return
+  [[ prevend -eq start ]] || { err "internal error in NotePartRegion ($prevstart-$prevend, $start-$end)"; exit 244; }
+  #echo "{$prevacc,$prevstart,$prevend}"
+  #echo "<$access,$start,$end>"
+  if [[ prevacc -eq access ]]; then let prevend=end+1; return
+  elif [[ prevacc -gt access ]]; then
+    let start=$(roundup prevend)
+    IssuePartRegion $prevacc $prevstart $start
+    [[ prevend -lt start && verbose -gt 1 ]] && warn "warning: access right extension $(acc2str $access)->$(acc2str $prevacc) $prevend..$((start-1))"
+  else # prevacc -lt access
+    let start=$(rounddown prevend)
+    IssuePartRegion $prevacc $prevstart $start
+    [[ start -lt prevend && verbose -gt 1 ]] && warn "warning: access right extension $(acc2str $prevacc)->$(acc2str $access) $start..$(($prevend-1))"
+  fi
+  let prevstart=start prevend=end+1 prevacc=access;
+}
+
+# global pos extstart extend
+
+NoteExtendedPartition() {
+  let extstart=$(rounddown $1) extend=$(roundup $(($2+1)))
+}
+
+skip() { local start=$1 extpos dstart;
+  if [[ extstart -lt extend ]]; then
+    let extpos=$(min $(max $pos $extstart) $start);
+    let dstart=$(max $(min $start $extend) $extpos); # diminished start position
+    NotePartRegion 0 $pos $((extpos-1))
+    NotePartRegion 1 $extpos $((dstart-1))
+    NotePartRegion 0 $dstart $((start-1))
+  else
+    NotePartRegion 0 $pos $((start-1))
+  fi
+}
 
 while [[ $# -gt 0 ]]; do
 case "$1" in
+  --version) echo "confinedrv 1.2.1"; echo;;
   -h|--help) echo -e "confinedrv [--ra] sdx=sda1,2,3,4 sdy=sdb1,2,3,4"
              echo -e "  --ra ... everything at least readable"
 	     echo -e "confinedrv -d/-r/--remove sdx sdy ...";
@@ -90,13 +179,17 @@ case "$1" in
   -d|-r|--remove) while [ -n "$2" ]; do
 		    drv="${2#/dev/mapper/}"
 		    dmsetup remove "$drv"
-		    droploop "$drv"; let ret+=$?
+		    droploop "$drv"; [[ $? -ne 0 ]] && let ret++
 		    shift
-		  done; exit $ret;;
+		  done; 
+		  exit $ret;;
+
   -i|--info) while [ -n "$2" ]; do
 	       echo "*** $2 ***"
 	       dmsetup status $2; echo; shift;
-	     done;;
+	     done;
+	     exit 0;;
+
   --ra) readall=true; shift; continue; ;;
   -v|--verbose) let verbose++; shift; continue; ;;
   -q|--quiet) let verbose--; shift; continue; ;;
@@ -113,107 +206,52 @@ parts[0]=${parts[0]#$org}; [[ -z "${parts[0]}" ]] && parts=();
 
 # echo $dest#$org#${#parts[@]}
 # echo ${parts[@]}
-# echo ----------
-# exit
+# echo ----------; exit
 
-getdevno() {
-  local attr x usr grp major minor rest
-  read attr x usr grp major minor rest < <(ls -l "$1";)
-  echo "${major%,}:$minor"
-}
-
-
-mkdir -p /dev/shm/
-#bdev=$(getdevno /dev/$org)
-if [[ ${#parts[@]} -gt 0 ]]; then
-  loop=$(losetup -f)
-  losetup $loop /dev/$org
-else loop="";
-fi
-
-rolp=$(losetup -f)
-losetup -r $rolp /dev/$org
-blockdev --setro $rolp
-chmod gua-w $rolp >/dev/null 2>&1 
-
-#echo "$dest $loop" >>/dev/shm/confinedrv-loops
-# -> later
-# fdisk -l reads block at 6422432/512 = 12543
-# part of sda1!
-
-# device mapper can only control access in chunks of pagesize = 4096 = 2**3*512
-
-alignstart() { let prevstart=start;
-  algnstart=$((start&~$PGspare))
-  if [[ pos -gt algnstart ]]; then let start=pos; # ok since space before already accessible
-                              else let start=algnstart; fi
-  #impossible: [[ pos -gt start ]] && { err "inconsistent input from fdisk; disks not ordered."; break; }
-  [[ verbose -ge 1 ]]&&[[ algnstart -ne start ]] && warn "aligned partition start from $prevstart to $start"
-}
-
-alignend() { let prevend=end;
-  algnend=$((end&~$PGspare))
-  if [[ pos -gt algnend ]]; then let end=pos; # ok since space before already accessible
-                            else let end=algnend; fi
-  #impossible: [[ pos -gt end ]] && { err "inconsistent input from fdisk; zero/minus space partition"; break; }
-  [[ verbose -ge 1 ]]&&[[ algnend -ne end ]] && warn "aligned partition end from $prevend to $end"
-}
-
-skip() {
-  if [[ pos -lt $1 ]]; then
-    if $extphead||$readall; 
-      then echo "$pos $(($1-pos)) linear $rolp $pos";
-      else echo "$pos $(($1-pos)) error"
-    fi
-  fi
-}
+initloops ${#parts[@]} 
 
 cleanup() {
-  sleep 0.3; rm "$drvtable"; [[ -n "$rolp" ]] && losetup -d $rolp; [[ -n "$loop" ]] && losetup -d $loop
+  sleep 0.3; rm "$drvtable"; [[ -n "$rolp" ]] && losetup -d $rolp; unset rolp; [[ -n "$loop" ]] && losetup -d $loop; unset loop;
 }
 
 drvtable="$(mktemp)"; trap "cleanup" EXIT
-pos=0; found=0; extphead=false; extpend=-1; maxdno=0;  #max=0;
+pos=0; prevacc=-1; prevstart=-1; prevend=0; extstart=-1; extend=-2; extwritable=false; found=0; maxdno=0;  #max=0;
 {
 while read dev start end blocks id type; do
   dno="${dev#/dev/$org}";
   if [ "$dev" != "$dno" ]; then 
     [[ dno -gt maxdno ]] && let maxdno=dno
     if [[ pos -eq 0 ]]; then
-      echo "0 $start linear $rolp 0"
-      pos=$start;
+      NotePartRegion 1 0 $start
+      let pos=start prevend=start
     fi
     #echo "$dev $pos $start" >&2
+
+    if [[ "${type#*Erw}" != "$type" || "${type#*Ext}" != "$type"  ]]; 
+      then isext=true; else isext=false; fi
+
+    if $extwritable && [[ extstart -le start && end -lt extend ]];
+      then continue; fi
+
     if ein $dno "${parts[@]}"; then
-      alignstart
       skip $start
-      echo "$start $((end-start+1)) linear $loop $start"
-      # not with alignment: echo "$start $((end+1-start)) linear /dev/$org$dno 0"
-      # if not aligned then dmsetup will extend attributes towards the end of partition
-      [[ extpend -le end ]] && extphead=false
-      pos=$((end+1)); let found++;
-      
-    elif [ "${type#*Erw}" != "$type" -o "${type#*Ext}" != "$type"  ]; then
-      alignstart
+      NotePartRegion 2 $start $end
+      let pos=end+1; let found++;
+      $isext && { extwritable=true; NoteExtendedPartition $start $end; }
+
+    elif $isext; then
+      NoteExtendedPartition $start $end
+
+    elif $readall; then
       skip $start
-      extphead=true; extpend=$end
-      pos=$start
-      
-    elif $extphead; then
-      let start+=$PGspare # aufrunden ! - extended partition head needs to be fully readable; danach kommt ausgeblendete Partition!
-      alignstart
+      NotePartRegion 1 $start $end
+      let pos=end+1;
+
+    else
       skip $start
-      pos=$start
-      
-      let end+=1;  # Anfang nächster: end + 1
-      extphead=false; # skip soll hier ausblenden (außer -a)
-      alignend;      # Platz für den Beginn der nächsten schaffen: nach vorne
-      skip $((end))  # skip bearbeitet bis eins vorher
-      extphead=true
-      [[ extpend -le end ]] && extphead=false
-      pos=$((end))
-      
-    #else echo "unprocessed: $dev" >&2;
+      NotePartRegion 0 $start $end
+      let pos=end+1;
+
     fi
     #[[ max -lt end ]] && let max=end
     #[[ min -gt start ]] && let min=start
@@ -221,9 +259,12 @@ while read dev start end blocks id type; do
 done < <( fdisk -lu -b 512 /dev/$org | tr '*' ' ' | sort -g -k 2 -s; ) 
 max=$(blockdev --getsz /dev/$org)
 skip $max
-} >"$drvtable"
+virtualdiskend=$(roundup $prevend)
+IssuePartRegion $prevacc $prevstart $virtualdiskend
 
-if [[ maxdno -ge 5 ]]&&[[ extpend -lt 0 ]]; then
+} 8>"$drvtable"
+
+if [[ maxdno -ge 5 && extpend -lt 0 ]]; then
   err "extended partitions found but no partition called '...Erw' or '...Ext' listed by fdisk -lu";
   echo "you may wish to correct the matching for the name of the exteneded partition in the sources" >&2;
   err "mapping will not function for extended partition"
